services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/usr/src/frontend/src:ro

    environment:
      - VITE_API_HOST=127.0.0.1
      - VITE_API_PORT=3001

  api:
    container_name: api
    restart: unless-stopped
    build: ./backend
    environment:
      - DEV_DATABASE_URL=postgres://dev_db:5432/dev_db?user=user&password=password
      - TEST_DATABASE_URL=postgres://test_db:5433/test_db?user=user&password=password
      - PORT=3001
    ports:
      - 3001:3001
    depends_on:
      - dev_db
      - test_db
    volumes:
      - ./backend/src:/usr/src/backend/src:ro

  dev_db:
    container_name: postgres_dev
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=dev_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432

  test_db:
    container_name: postgres_test
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./sql/create-test-tables.sql:/docker-entrypoint-initdb.d/create-test-tables.sql:ro
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5433
volumes:
  data: {}
