services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5173:5173
    # volumes:
    # - .:/frontend:/usr/src/frontend
    environment:
      - VITE_API_HOST=127.0.0.1
      - VITE_API_PORT=3001
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /usr/src/frontend/src
  api:
    container_name: api
    restart: unless-stopped
    build: ./backend
    environment:
      - PORT=3001
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    ports:
      - 3001:3001
    depends_on:
      - db
    # volumes:
    # - .:/backend:/usr/src/backend
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/src/backend/src
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432

volumes:
  data: {}
