services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/usr/src/frontend/src:ro

    environment:
      - VITE_API_HOST=127.0.0.1
      - VITE_API_PORT=3001

  api:
    container_name: api
    restart: unless-stopped
    build: ./backend
    environment:
      - DATABASE_URL=postgres://db:5432/db_name?user=user&password=password
      - PORT=3001
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./backend/src:/usr/src/backend/src:ro

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db_name
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432

volumes:
  data: {}
